blank_issues_enabled: false
contact_links:
  - name: ğŸ‘¾ Chat
    url: https://t.me/astro_pure
    about: Chat with the community on Telegram
  - name: ğŸ“˜ Documentation
    url: https://astro-pure.js.org/docs
    about: Checkout the documentation for more information
  - name: ğŸ’ Discussion
    url: https://github.com/cworld1/astro-theme-pure/discussions
    about: 'This issue tracker is not for support questions. Leave a comment on the discussion board if you need help.'
